---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Uses same as updater
    iam.gke.io/gcp-service-account: testgrid-canary@k8s-testgrid.iam.gserviceaccount.com
  name: summarizer
  namespace: testgrid-canary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-summarizer
  namespace: testgrid-canary
  labels:
    app: testgrid
    channel: stable
    component: summarizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      channel: stable
      component: summarizer
  template:
    metadata:
      labels:
        app: testgrid
        channel: stable
        component: summarizer
    spec:
      serviceAccountName: summarizer
      containers:
      - name: summarizer
        image: gcr.io/k8s-testgrid/summarizer:v20211119-v0.0.110-15-g281365f
        ports:
        - name: metrics
          containerPort: 2112
        args:
        - --config=gs://k8s-testgrid-canary/config
        - --confirm
        - --grid-path=grid
        - --json-logs
        - --pubsub=k8s-testgrid/canary-test-group-updates
        - --summary-path=summary
        - --wait=1h
        resources:
          requests:
            cpu: "1"
            memory: "50G"
          limits:
            cpu: "2"
            memory: "100G"
---
