---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Uses same as updater
    iam.gke.io/gcp-service-account: testgrid-canary@k8s-testgrid.iam.gserviceaccount.com
  name: summarizer
  namespace: testgrid-canary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-summarizer-tabs
  namespace: testgrid-canary
  labels:
    app: testgrid
    channel: stable
    component: summarizer-tabs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      channel: stable
      component: summarizer-tabs
  template:
    metadata:
      labels:
        app: testgrid
        channel: stable
        component: summarizer-tabs
    spec:
      serviceAccountName: summarizer
      containers:
      - name: summarizer
        image: gcr.io/k8s-testgrid/summarizer:v20220630-v0.0.143-8-g28bab077
        ports:
        - name: metrics
          containerPort: 2112
        args:
        - --config=gs://k8s-testgrid-canary/config
        - --confirm
        - --json-logs
        - --persist-queue=gs://k8s-testgrid-canary/queue/summarizer-tabs.json
        - --pubsub=k8s-testgrid/canary-tab-updates
        - --wait=1h
        resources:
          requests:
            cpu: "1"
            memory: "50G"
          limits:
            cpu: "2"
            memory: "100G"
---
