---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-summarizer
  namespace: testgrid-canary
  labels:
    app: testgrid
    channel: stable
    component: summarizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      channel: stable
      component: summarizer
  template:
    metadata:
      labels:
        app: testgrid
        channel: stable
        component: summarizer
    spec:
      serviceAccountName: summarizer
      containers:
      - name: summarizer
        image: gcr.io/k8s-testgrid/summarizer:v20210405-v0.0.58-18-g848f281 
        args:
        - --config=gs://k8s-testgrid-canary/config
        - --confirm
        # TODO(fejta): next release: --json-logs
        - --wait=1h
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta-summarizer
  namespace: testgrid-canary
  labels:
    app: testgrid
    channel: beta
    component: summarizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      channel: beta
      component: summarizer
  template:
    metadata:
      labels:
        app: testgrid
        channel: beta
        component: summarizer
    spec:
      serviceAccountName: summarizer
      containers:
      - name: summarizer
        image: gcr.io/k8s-testgrid/summarizer:v20210405-v0.0.58-18-g848f281
        args:
        - --config=gs://k8s-testgrid-canary/config
        - --confirm
        - --grid-path=grid
        # TODO(fejta): next release: --json-logs
        - --summary-path=summary
        - --wait=1h
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Uses same as updater
    iam.gke.io/gcp-service-account: testgrid-canary@k8s-testgrid.iam.gserviceaccount.com
  name: summarizer
  namespace: testgrid-canary
