---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-tabulator
  namespace: testgrid-canary
  labels:
    app: testgrid
    channel: stable
    component: tabulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      channel: stable
      component: tabulator
  template:
    metadata:
      labels:
        app: testgrid
        channel: stable
        component: tabulator
    spec:
      serviceAccountName: tabulator
      containers:
      - name: tabulator
        image: gcr.io/k8s-testgrid/tabulator:v20220408-v0.0.131-4-g8245be5f
        ports:
        - name: metrics
          containerPort: 2112
        args:
        - --config=gs://k8s-testgrid-canary/config
        - --confirm
        - --wait=15m
        - --pubsub=k8s-testgrid/canary-test-group-updates
        - --persist-queue=gs://k8s-testgrid-canary/queue/tabulator.json
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Uses same as updater
    iam.gke.io/gcp-service-account: testgrid-canary@k8s-testgrid.iam.gserviceaccount.com
  name: tabulator
  namespace: testgrid-canary
