---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: testgrid-canary@k8s-testgrid.iam.gserviceaccount.com
  name: updater
  namespace: testgrid-canary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-updater
  namespace: testgrid-canary
  labels:
    component: updater
    app: testgrid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testgrid
      component: updater
  template:
    metadata:
      labels:
        component: updater
        app: testgrid
    spec:
      serviceAccountName: updater
      containers:
      - name: updater
        image: gcr.io/k8s-testgrid/updater:v20210811-v0.0.90-22-gb144ff6 
        args:
        - --build-concurrency=2
        - --build-timeout=2m
        - --config=gs://k8s-testgrid-canary/config
        - --confirm
        - --group-concurrency=4
        - --group-timeout=10m
        - --json-logs
        - --subscribe=kubernetes-jenkins=kubernetes-jenkins/testgrid
        - --subscribe=oss-prow=k8s-testgrid/testgrid-canary
        - --subscribe=istio-prow=k8s-testgrid/testgrid-canary
        - --wait=3h
        resources:
          requests:
            cpu: "1"
            memory: "50G"
          limits:
            cpu: "4"
            memory: "100G"
---
