---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-updater
  namespace: testgrid-canary
  labels:
    component: updater
    app: testgrid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      component: updater
  template:
    metadata:
      labels:
        component: updater
        app: testgrid
    spec:
      serviceAccountName: updater
      containers:
      - name: updater
        image: gcr.io/k8s-testgrid/updater:v20201203-v0.0.31-5-g5f8e850
        args:
        - --build-timeout=10m
        - --config=gs://k8s-testgrid-canary/config
        - --confirm
        - --group-timeout=60m
        - --wait=5m
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: testgrid-canary@k8s-testgrid.iam.gserviceaccount.com
  name: updater
  namespace: testgrid-canary
