presubmits:
- name: test-testgrid-all
  decorate: true
  always_run: true
  spec:
    serviceAccountName: presubmits
    containers:
    - image: gcr.io/k8s-testgrid/gcloud-bazel:v20220613-v0.6-58-ge5a50c7
      command:
      - bazel
      args:
      - test
      - --config=ci
      - //...
- name: test-testgrid-npm
  decorate: true
  always_run: true
  spec:
    serviceAccountName: presubmits
    containers:
    # See https://playwright.dev/docs/ci
    - image: mcr.microsoft.com/playwright:v1.32.0-focal
      command:
      - bash
      args:
      - -c
      - cd web && npm install -g json-server && npm install && npm run build && json-server src/fake-api/data.json --routes src/fake-api/routes.json  && npm run test
