/*
Copyright The TestGrid Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: summary.proto

package summary

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DashboardTabSummary_TabStatus int32

const (
	DashboardTabSummary_NOT_SET DashboardTabSummary_TabStatus = 0
	DashboardTabSummary_UNKNOWN DashboardTabSummary_TabStatus = 1
	DashboardTabSummary_PASS    DashboardTabSummary_TabStatus = 2
	DashboardTabSummary_FAIL    DashboardTabSummary_TabStatus = 3
	DashboardTabSummary_FLAKY   DashboardTabSummary_TabStatus = 4
	DashboardTabSummary_STALE   DashboardTabSummary_TabStatus = 5
	DashboardTabSummary_BROKEN  DashboardTabSummary_TabStatus = 6
)

var DashboardTabSummary_TabStatus_name = map[int32]string{
	0: "NOT_SET",
	1: "UNKNOWN",
	2: "PASS",
	3: "FAIL",
	4: "FLAKY",
	5: "STALE",
	6: "BROKEN",
}

var DashboardTabSummary_TabStatus_value = map[string]int32{
	"NOT_SET": 0,
	"UNKNOWN": 1,
	"PASS":    2,
	"FAIL":    3,
	"FLAKY":   4,
	"STALE":   5,
	"BROKEN":  6,
}

func (x DashboardTabSummary_TabStatus) String() string {
	return proto.EnumName(DashboardTabSummary_TabStatus_name, int32(x))
}

func (DashboardTabSummary_TabStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7168d0e3f3f5589, []int{1, 0}
}

// Summary of a failing test.
type FailingTestSummary struct {
	// Display name of the test.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Name of the test. E.g., the target for tests in Sponge.
	TestName string `protobuf:"bytes,2,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	// First build ID at which the test failed.
	FailBuildId string `protobuf:"bytes,3,opt,name=fail_build_id,json=failBuildId,proto3" json:"fail_build_id,omitempty"`
	// Timestamp for the first cycle in which the test failed.
	FailTimestamp float64 `protobuf:"fixed64,4,opt,name=fail_timestamp,json=failTimestamp,proto3" json:"fail_timestamp,omitempty"`
	// Last build ID at which the test passed.
	PassBuildId string `protobuf:"bytes,5,opt,name=pass_build_id,json=passBuildId,proto3" json:"pass_build_id,omitempty"`
	// Timestamp for the last cycle in which the test passed.
	PassTimestamp float64 `protobuf:"fixed64,6,opt,name=pass_timestamp,json=passTimestamp,proto3" json:"pass_timestamp,omitempty"`
	// Number of times the test has failed.
	FailCount int32 `protobuf:"varint,7,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	// Link to search for build changes.
	BuildLink string `protobuf:"bytes,8,opt,name=build_link,json=buildLink,proto3" json:"build_link,omitempty"`
	// Text for option to search for build changes.
	BuildLinkText string `protobuf:"bytes,9,opt,name=build_link_text,json=buildLinkText,proto3" json:"build_link_text,omitempty"`
	// Text to display for link to search for build changes.
	BuildUrlText string `protobuf:"bytes,10,opt,name=build_url_text,json=buildUrlText,proto3" json:"build_url_text,omitempty"`
	// Text for failure statuses associated with this test.
	FailureMessage string `protobuf:"bytes,11,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	// List of bug IDs for bugs associated with this test.
	LinkedBugs []string `protobuf:"bytes,12,rep,name=linked_bugs,json=linkedBugs,proto3" json:"linked_bugs,omitempty"`
	// A link to the first build in which the test failed.
	FailTestLink         string   `protobuf:"bytes,13,opt,name=fail_test_link,json=failTestLink,proto3" json:"fail_test_link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailingTestSummary) Reset()         { *m = FailingTestSummary{} }
func (m *FailingTestSummary) String() string { return proto.CompactTextString(m) }
func (*FailingTestSummary) ProtoMessage()    {}
func (*FailingTestSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7168d0e3f3f5589, []int{0}
}

func (m *FailingTestSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailingTestSummary.Unmarshal(m, b)
}
func (m *FailingTestSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailingTestSummary.Marshal(b, m, deterministic)
}
func (m *FailingTestSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailingTestSummary.Merge(m, src)
}
func (m *FailingTestSummary) XXX_Size() int {
	return xxx_messageInfo_FailingTestSummary.Size(m)
}
func (m *FailingTestSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_FailingTestSummary.DiscardUnknown(m)
}

var xxx_messageInfo_FailingTestSummary proto.InternalMessageInfo

func (m *FailingTestSummary) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *FailingTestSummary) GetTestName() string {
	if m != nil {
		return m.TestName
	}
	return ""
}

func (m *FailingTestSummary) GetFailBuildId() string {
	if m != nil {
		return m.FailBuildId
	}
	return ""
}

func (m *FailingTestSummary) GetFailTimestamp() float64 {
	if m != nil {
		return m.FailTimestamp
	}
	return 0
}

func (m *FailingTestSummary) GetPassBuildId() string {
	if m != nil {
		return m.PassBuildId
	}
	return ""
}

func (m *FailingTestSummary) GetPassTimestamp() float64 {
	if m != nil {
		return m.PassTimestamp
	}
	return 0
}

func (m *FailingTestSummary) GetFailCount() int32 {
	if m != nil {
		return m.FailCount
	}
	return 0
}

func (m *FailingTestSummary) GetBuildLink() string {
	if m != nil {
		return m.BuildLink
	}
	return ""
}

func (m *FailingTestSummary) GetBuildLinkText() string {
	if m != nil {
		return m.BuildLinkText
	}
	return ""
}

func (m *FailingTestSummary) GetBuildUrlText() string {
	if m != nil {
		return m.BuildUrlText
	}
	return ""
}

func (m *FailingTestSummary) GetFailureMessage() string {
	if m != nil {
		return m.FailureMessage
	}
	return ""
}

func (m *FailingTestSummary) GetLinkedBugs() []string {
	if m != nil {
		return m.LinkedBugs
	}
	return nil
}

func (m *FailingTestSummary) GetFailTestLink() string {
	if m != nil {
		return m.FailTestLink
	}
	return ""
}

// Summary of a dashboard tab.
type DashboardTabSummary struct {
	// The name of the dashboard.
	DashboardName string `protobuf:"bytes,1,opt,name=dashboard_name,json=dashboardName,proto3" json:"dashboard_name,omitempty"`
	// The name of the dashboard tab.
	DashboardTabName string `protobuf:"bytes,2,opt,name=dashboard_tab_name,json=dashboardTabName,proto3" json:"dashboard_tab_name,omitempty"`
	// Any top-level alert on this dashboard tab.
	Alert string `protobuf:"bytes,3,opt,name=alert,proto3" json:"alert,omitempty"`
	// List of failing test summary information.
	FailingTestSummaries []*FailingTestSummary `protobuf:"bytes,4,rep,name=failing_test_summaries,json=failingTestSummaries,proto3" json:"failing_test_summaries,omitempty"`
	// Seconds since epoch at which the test group was last updated.
	LastUpdateTimestamp float64 `protobuf:"fixed64,5,opt,name=last_update_timestamp,json=lastUpdateTimestamp,proto3" json:"last_update_timestamp,omitempty"`
	// A summary of the status of this dashboard tab.
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// The overall status for this dashboard tab.
	OverallStatus DashboardTabSummary_TabStatus `protobuf:"varint,7,opt,name=overall_status,json=overallStatus,proto3,enum=DashboardTabSummary_TabStatus" json:"overall_status,omitempty"`
	// The ID for the latest passing build.
	LatestGreen string `protobuf:"bytes,8,opt,name=latest_green,json=latestGreen,proto3" json:"latest_green,omitempty"`
	// Seconds since epoch at which tests last ran.
	LastRunTimestamp float64 `protobuf:"fixed64,9,opt,name=last_run_timestamp,json=lastRunTimestamp,proto3" json:"last_run_timestamp,omitempty"`
	// String indicating the URL for linking to a bug.
	BugUrl               string   `protobuf:"bytes,10,opt,name=bug_url,json=bugUrl,proto3" json:"bug_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DashboardTabSummary) Reset()         { *m = DashboardTabSummary{} }
func (m *DashboardTabSummary) String() string { return proto.CompactTextString(m) }
func (*DashboardTabSummary) ProtoMessage()    {}
func (*DashboardTabSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7168d0e3f3f5589, []int{1}
}

func (m *DashboardTabSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardTabSummary.Unmarshal(m, b)
}
func (m *DashboardTabSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardTabSummary.Marshal(b, m, deterministic)
}
func (m *DashboardTabSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardTabSummary.Merge(m, src)
}
func (m *DashboardTabSummary) XXX_Size() int {
	return xxx_messageInfo_DashboardTabSummary.Size(m)
}
func (m *DashboardTabSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardTabSummary.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardTabSummary proto.InternalMessageInfo

func (m *DashboardTabSummary) GetDashboardName() string {
	if m != nil {
		return m.DashboardName
	}
	return ""
}

func (m *DashboardTabSummary) GetDashboardTabName() string {
	if m != nil {
		return m.DashboardTabName
	}
	return ""
}

func (m *DashboardTabSummary) GetAlert() string {
	if m != nil {
		return m.Alert
	}
	return ""
}

func (m *DashboardTabSummary) GetFailingTestSummaries() []*FailingTestSummary {
	if m != nil {
		return m.FailingTestSummaries
	}
	return nil
}

func (m *DashboardTabSummary) GetLastUpdateTimestamp() float64 {
	if m != nil {
		return m.LastUpdateTimestamp
	}
	return 0
}

func (m *DashboardTabSummary) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DashboardTabSummary) GetOverallStatus() DashboardTabSummary_TabStatus {
	if m != nil {
		return m.OverallStatus
	}
	return DashboardTabSummary_NOT_SET
}

func (m *DashboardTabSummary) GetLatestGreen() string {
	if m != nil {
		return m.LatestGreen
	}
	return ""
}

func (m *DashboardTabSummary) GetLastRunTimestamp() float64 {
	if m != nil {
		return m.LastRunTimestamp
	}
	return 0
}

func (m *DashboardTabSummary) GetBugUrl() string {
	if m != nil {
		return m.BugUrl
	}
	return ""
}

// Summary state of a dashboard.
type DashboardSummary struct {
	// Summary of a dashboard tab; see config.proto.
	TabSummaries         []*DashboardTabSummary `protobuf:"bytes,1,rep,name=tab_summaries,json=tabSummaries,proto3" json:"tab_summaries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DashboardSummary) Reset()         { *m = DashboardSummary{} }
func (m *DashboardSummary) String() string { return proto.CompactTextString(m) }
func (*DashboardSummary) ProtoMessage()    {}
func (*DashboardSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7168d0e3f3f5589, []int{2}
}

func (m *DashboardSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardSummary.Unmarshal(m, b)
}
func (m *DashboardSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardSummary.Marshal(b, m, deterministic)
}
func (m *DashboardSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardSummary.Merge(m, src)
}
func (m *DashboardSummary) XXX_Size() int {
	return xxx_messageInfo_DashboardSummary.Size(m)
}
func (m *DashboardSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardSummary.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardSummary proto.InternalMessageInfo

func (m *DashboardSummary) GetTabSummaries() []*DashboardTabSummary {
	if m != nil {
		return m.TabSummaries
	}
	return nil
}

func init() {
	proto.RegisterEnum("DashboardTabSummary_TabStatus", DashboardTabSummary_TabStatus_name, DashboardTabSummary_TabStatus_value)
	proto.RegisterType((*FailingTestSummary)(nil), "FailingTestSummary")
	proto.RegisterType((*DashboardTabSummary)(nil), "DashboardTabSummary")
	proto.RegisterType((*DashboardSummary)(nil), "DashboardSummary")
}

func init() { proto.RegisterFile("summary.proto", fileDescriptor_f7168d0e3f3f5589) }

var fileDescriptor_f7168d0e3f3f5589 = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x49, 0xf3, 0xa7, 0xf1, 0x38, 0x4e, 0xad, 0x6d, 0x29, 0x96, 0x10, 0x10, 0x22, 0x0a,
	0x39, 0xa0, 0x1c, 0xca, 0x89, 0x63, 0x0a, 0x29, 0x2a, 0x4d, 0x53, 0xe4, 0x38, 0x42, 0x88, 0x83,
	0xb5, 0xc6, 0x5b, 0x63, 0xd5, 0x76, 0x22, 0xef, 0x2e, 0x6a, 0x9f, 0x89, 0xf7, 0xe2, 0x39, 0xd0,
	0xcc, 0x3a, 0x71, 0x04, 0xbd, 0xed, 0xfe, 0xe6, 0xf3, 0xcc, 0xec, 0x7c, 0x93, 0x80, 0x23, 0x75,
	0x9e, 0xf3, 0xf2, 0x7e, 0xbc, 0x2e, 0x57, 0x6a, 0x35, 0xfc, 0xd3, 0x04, 0x76, 0xce, 0xd3, 0x2c,
	0x2d, 0x92, 0x40, 0x48, 0xb5, 0x30, 0x41, 0xf6, 0x12, 0x7a, 0x71, 0x2a, 0xd7, 0x19, 0xbf, 0x0f,
	0x0b, 0x9e, 0x0b, 0xaf, 0x31, 0x68, 0x8c, 0x2c, 0xdf, 0xae, 0xd8, 0x9c, 0xe7, 0x82, 0x3d, 0x05,
	0x4b, 0x09, 0xa9, 0x4c, 0x7c, 0x8f, 0xe2, 0x5d, 0x04, 0x14, 0x1c, 0x82, 0x73, 0xc3, 0xd3, 0x2c,
	0x8c, 0x74, 0x9a, 0xc5, 0x61, 0x1a, 0x7b, 0x4d, 0x93, 0x00, 0xe1, 0x19, 0xb2, 0x8b, 0x98, 0x9d,
	0x40, 0x9f, 0x34, 0x2a, 0xcd, 0x85, 0x54, 0x3c, 0x5f, 0x7b, 0xad, 0x41, 0x63, 0xd4, 0xf0, 0xe9,
	0xcb, 0x60, 0x03, 0x31, 0xd5, 0x9a, 0x4b, 0x59, 0xa7, 0x6a, 0x9b, 0x54, 0x08, 0x77, 0x52, 0x91,
	0xa6, 0x4e, 0xd5, 0x31, 0xa9, 0x90, 0xd6, 0xa9, 0x9e, 0x01, 0x50, 0xc5, 0x1f, 0x2b, 0x5d, 0x28,
	0x6f, 0x7f, 0xd0, 0x18, 0xb5, 0x7d, 0x0b, 0xc9, 0x07, 0x04, 0x18, 0x36, 0x45, 0xb2, 0xb4, 0xb8,
	0xf5, 0xba, 0x54, 0xc6, 0x22, 0x32, 0x4b, 0x8b, 0x5b, 0xf6, 0x1a, 0x0e, 0xea, 0x70, 0xa8, 0xc4,
	0x9d, 0xf2, 0x2c, 0xd2, 0x38, 0x5b, 0x4d, 0x20, 0xee, 0x14, 0x7b, 0x05, 0x7d, 0xa3, 0xd3, 0x65,
	0x66, 0x64, 0x40, 0xb2, 0x1e, 0xd1, 0x65, 0x99, 0x91, 0xea, 0x0d, 0x1c, 0x60, 0x65, 0x5d, 0x8a,
	0x30, 0x17, 0x52, 0xf2, 0x44, 0x78, 0x36, 0xc9, 0xfa, 0x15, 0xbe, 0x32, 0x94, 0xbd, 0x00, 0x1b,
	0x0b, 0x8a, 0x38, 0x8c, 0x74, 0x22, 0xbd, 0xde, 0xa0, 0x39, 0xb2, 0x7c, 0x30, 0xe8, 0x4c, 0x27,
	0x12, 0xeb, 0x99, 0x39, 0xa2, 0x1b, 0xd4, 0xba, 0x63, 0xea, 0xd1, 0x1c, 0x85, 0x54, 0xd8, 0xd9,
	0xf0, 0x77, 0x0b, 0x0e, 0x3f, 0x72, 0xf9, 0x33, 0x5a, 0xf1, 0x32, 0x0e, 0x78, 0xb4, 0x71, 0xfa,
	0x04, 0xfa, 0xf1, 0x06, 0xef, 0x7a, 0xed, 0x6c, 0x29, 0x19, 0xfa, 0x16, 0x58, 0x2d, 0x53, 0x3c,
	0xda, 0xb5, 0xdd, 0x8d, 0x77, 0xf2, 0x92, 0xfa, 0x08, 0xda, 0x3c, 0x13, 0xa5, 0xaa, 0x6c, 0x37,
	0x17, 0x76, 0x01, 0xc7, 0x37, 0x66, 0xd5, 0x4c, 0xaf, 0x66, 0x13, 0x53, 0x21, 0xbd, 0xd6, 0xa0,
	0x39, 0xb2, 0x4f, 0x0f, 0xc7, 0xff, 0x6f, 0xa2, 0x7f, 0x74, 0xf3, 0x2f, 0x4b, 0x85, 0x64, 0xa7,
	0xf0, 0x38, 0xe3, 0x52, 0x85, 0x7a, 0x1d, 0x73, 0x25, 0x76, 0x7c, 0x6f, 0x93, 0xef, 0x87, 0x18,
	0x5c, 0x52, 0xac, 0x76, 0xff, 0x18, 0x3a, 0x52, 0x71, 0xa5, 0x25, 0x2d, 0x87, 0xe5, 0x57, 0x37,
	0x36, 0x85, 0xfe, 0xea, 0x97, 0x28, 0x79, 0x96, 0x85, 0x55, 0x1c, 0x37, 0xa3, 0x7f, 0xfa, 0x7c,
	0xfc, 0xc0, 0xbc, 0xc6, 0x78, 0x24, 0x95, 0xef, 0x54, 0x5f, 0x99, 0x2b, 0xfe, 0x64, 0x32, 0x4e,
	0xef, 0x4a, 0x4a, 0x21, 0x8a, 0x6a, 0x7f, 0x6c, 0xc3, 0x3e, 0x21, 0xc2, 0x21, 0x52, 0xd7, 0xa5,
	0x2e, 0x76, 0x5a, 0xb6, 0xa8, 0x65, 0x17, 0x23, 0xbe, 0x2e, 0xea, 0x7e, 0x9f, 0xc0, 0x7e, 0xa4,
	0x13, 0xdc, 0xa2, 0x6a, 0x81, 0x3a, 0x91, 0x4e, 0x96, 0x65, 0x36, 0xfc, 0x0e, 0xd6, 0xb6, 0x0b,
	0x66, 0xc3, 0xfe, 0xfc, 0x3a, 0x08, 0x17, 0xd3, 0xc0, 0x7d, 0x84, 0x97, 0xe5, 0xfc, 0x72, 0x7e,
	0xfd, 0x75, 0xee, 0x36, 0x58, 0x17, 0x5a, 0x5f, 0x26, 0x8b, 0x85, 0xbb, 0x87, 0xa7, 0xf3, 0xc9,
	0xc5, 0xcc, 0x6d, 0x32, 0x0b, 0xda, 0xe7, 0xb3, 0xc9, 0xe5, 0x37, 0xb7, 0x85, 0xc7, 0x45, 0x30,
	0x99, 0x4d, 0xdd, 0x36, 0x03, 0xe8, 0x9c, 0xf9, 0xd7, 0x97, 0xd3, 0xb9, 0xdb, 0xf9, 0xdc, 0xea,
	0xda, 0x6e, 0x6f, 0x78, 0x05, 0xee, 0xf6, 0xf1, 0x9b, 0x4d, 0x79, 0x0f, 0x0e, 0x1a, 0x5f, 0xbb,
	0xd6, 0x20, 0xd7, 0x8e, 0x1e, 0x1a, 0x93, 0xdf, 0x53, 0x9b, 0x73, 0x2a, 0x64, 0xd4, 0xa1, 0x3f,
	0x9b, 0x77, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x89, 0x97, 0x1d, 0x7d, 0x04, 0x00, 0x00,
}
