---
gitHubLogin: "google-oss-robot"
gitHubToken: "/etc/github-token/oauth"
onCallAddress: "https://storage.googleapis.com/kubernetes-jenkins/oncall.json"
skipPullRequest: false
skipOncallAssignment: true
gitHubOrg: "GoogleCloudPlatform"
gitHubRepo: "testgrid"
remoteName: "testgrid"
headBranchName: "autobump-prod"
upstreamURLBase: "https://raw.githubusercontent.com/GoogleCloudPlatform/testgrid/master"
includedConfigPaths:
  - "cluster/prod"
targetVersion: "upstream"
prefixes:
  - name: "Testgrid Prod"
    prefix: "gcr.io/k8s-testgrid/"
    refConfigFile: "cluster/canary/summarizer.yaml"
    repo: "https://github.com/GoogleCloudPlatform/testgrid"
    summarise: true
    consistentImages: true
