---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-tabulator
  namespace: testgrid
  labels:
    app: testgrid
    channel: stable
    component: tabulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      channel: stable
      component: tabulator
  template:
    metadata:
      labels:
        app: testgrid
        channel: stable
        component: tabulator
    spec:
      serviceAccountName: tabulator
      containers:
      - name: tabulator
        image: gcr.io/k8s-testgrid/tabulator:v20220420-v0.0.135-6-g2d6af93a
        ports:
        - name: metrics
          containerPort: 2112
        args:
        - --config=gs://k8s-testgrid/config
        - --confirm
        - --pubsub=k8s-testgrid/test-group-updates
        - --persist-queue=gs://k8s-testgrid/queue/tabulator.json
        - --wait=1h
        - --filter
        resources:
          requests:
            cpu: "30"
            memory: "75G"
          limits:
            cpu: "40"
            memory: "150G"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Uses same as updater
    iam.gke.io/gcp-service-account: updater@k8s-testgrid.iam.gserviceaccount.com
  name: tabulator
  namespace: testgrid
