---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: updater@k8s-testgrid.iam.gserviceaccount.com
  name: updater
  namespace: testgrid
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-updater
  namespace: testgrid
  labels:
    component: updater
    app: testgrid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testgrid
      component: updater
  template:
    metadata:
      labels:
        component: updater
        app: testgrid
    spec:
      serviceAccountName: updater
      containers:
      - name: updater
        image: gcr.io/k8s-testgrid/updater:v20210817-v0.0.91-14-gb2da23e
        args:
        - --build-concurrency=2
        - --build-timeout=2m
        - --config=gs://k8s-testgrid/config
        - --confirm
        - --group-concurrency=4
        - --group-timeout=10m
        - --json-logs
        - --subscribe=kubernetes-jenkins=kubernetes-jenkins/testgrid
        - --subscribe=oss-prow=k8s-testgrid/testgrid
        - --subscribe=istio-prow=k8s-testgrid/testgrid
        - --wait=2h
        resources:
          requests:
            cpu: "5"
            memory: "20G"
          limits:
            cpu: "10"
            memory: "50G"
---
