---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-updater
  namespace: testgrid
  labels:
    component: updater
    app: testgrid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testgrid
      component: updater
  template:
    metadata:
      labels:
        component: updater
        app: testgrid
    spec:
      serviceAccountName: updater
      containers:
      - name: updater
        image: gcr.io/k8s-testgrid/updater:v20210125-v0.0.41-2-gce1b140
        args:
        - --build-timeout=1m
        - --config=gs://k8s-testgrid/config
        - --confirm
        - --group-timeout=5m
        - --wait=5m
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: updater@k8s-testgrid.iam.gserviceaccount.com
  name: updater
  namespace: testgrid
