---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-updater
  namespace: testgrid
  labels:
    component: updater
    app: testgrid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testgrid
      component: updater
  template:
    metadata:
      labels:
        component: updater
        app: testgrid
    spec:
      serviceAccountName: updater
      containers:
      - name: updater
        image: gcr.io/k8s-testgrid/updater:v20210723-v0.0.82-2-g1da93b3
        args:
        - --build-timeout=2m
        - --build-concurrency=2
        - --group-concurrency=4
        - --config=gs://k8s-testgrid/config
        - --confirm
        - --json-logs
        - --group-timeout=10m
        - --wait=10m
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: updater@k8s-testgrid.iam.gserviceaccount.com
  name: updater
  namespace: testgrid
