/*
Copyright The TestGrid Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package testgrid_api_v1

import (
	fmt "fmt"
	config "github.com/GoogleCloudPlatform/testgrid/pb/config"
	state "github.com/GoogleCloudPlatform/testgrid/pb/state"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GET /dashboards
// Lists dashboard names
type ListDashboardResponse struct {
	Dashboards           []*Resource `protobuf:"bytes,1,rep,name=dashboards,proto3" json:"dashboards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListDashboardResponse) Reset()         { *m = ListDashboardResponse{} }
func (m *ListDashboardResponse) String() string { return proto.CompactTextString(m) }
func (*ListDashboardResponse) ProtoMessage()    {}
func (*ListDashboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *ListDashboardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDashboardResponse.Unmarshal(m, b)
}
func (m *ListDashboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDashboardResponse.Marshal(b, m, deterministic)
}
func (m *ListDashboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDashboardResponse.Merge(m, src)
}
func (m *ListDashboardResponse) XXX_Size() int {
	return xxx_messageInfo_ListDashboardResponse.Size(m)
}
func (m *ListDashboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDashboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDashboardResponse proto.InternalMessageInfo

func (m *ListDashboardResponse) GetDashboards() []*Resource {
	if m != nil {
		return m.Dashboards
	}
	return nil
}

// GET /dashboardgroups
// Lists the dashboard group names
type ListDashboardGroupResponse struct {
	DashboardGroups      []*Resource `protobuf:"bytes,1,rep,name=dashboard_groups,json=dashboardGroups,proto3" json:"dashboard_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListDashboardGroupResponse) Reset()         { *m = ListDashboardGroupResponse{} }
func (m *ListDashboardGroupResponse) String() string { return proto.CompactTextString(m) }
func (*ListDashboardGroupResponse) ProtoMessage()    {}
func (*ListDashboardGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *ListDashboardGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDashboardGroupResponse.Unmarshal(m, b)
}
func (m *ListDashboardGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDashboardGroupResponse.Marshal(b, m, deterministic)
}
func (m *ListDashboardGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDashboardGroupResponse.Merge(m, src)
}
func (m *ListDashboardGroupResponse) XXX_Size() int {
	return xxx_messageInfo_ListDashboardGroupResponse.Size(m)
}
func (m *ListDashboardGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDashboardGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDashboardGroupResponse proto.InternalMessageInfo

func (m *ListDashboardGroupResponse) GetDashboardGroups() []*Resource {
	if m != nil {
		return m.DashboardGroups
	}
	return nil
}

// GET /dashboards/{dashboard}/tabs
// Lists the dashboard tab names
type ListDashboardTabsResponse struct {
	DashboardTabs        []*Resource `protobuf:"bytes,1,rep,name=dashboard_tabs,json=dashboardTabs,proto3" json:"dashboard_tabs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListDashboardTabsResponse) Reset()         { *m = ListDashboardTabsResponse{} }
func (m *ListDashboardTabsResponse) String() string { return proto.CompactTextString(m) }
func (*ListDashboardTabsResponse) ProtoMessage()    {}
func (*ListDashboardTabsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *ListDashboardTabsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDashboardTabsResponse.Unmarshal(m, b)
}
func (m *ListDashboardTabsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDashboardTabsResponse.Marshal(b, m, deterministic)
}
func (m *ListDashboardTabsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDashboardTabsResponse.Merge(m, src)
}
func (m *ListDashboardTabsResponse) XXX_Size() int {
	return xxx_messageInfo_ListDashboardTabsResponse.Size(m)
}
func (m *ListDashboardTabsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDashboardTabsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDashboardTabsResponse proto.InternalMessageInfo

func (m *ListDashboardTabsResponse) GetDashboardTabs() []*Resource {
	if m != nil {
		return m.DashboardTabs
	}
	return nil
}

// GET /dashboards/{dashboard}
// Returns a Dashboard config's metadata
// Excludes subtabs, accessed through the /tabs list method instead
type GetDashboardResponse struct {
	// A list of notifications attached to this dashboard.
	// This is displayed on any dashboard tab in this dashboard.
	Notifications []*config.Notification `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	// Control which tab is displayed when first opening a dashboard.
	// Defaults to Summary
	DefaultTab string `protobuf:"bytes,2,opt,name=default_tab,json=defaultTab,proto3" json:"default_tab,omitempty"`
	// Controls whether to suppress highlighting of failing tabs.
	SuppressFailingTabs bool `protobuf:"varint,3,opt,name=suppress_failing_tabs,json=suppressFailingTabs,proto3" json:"suppress_failing_tabs,omitempty"`
	// Controls whether to apply special highlighting to result header columns for
	// the current day.
	HighlightToday       bool     `protobuf:"varint,4,opt,name=highlight_today,json=highlightToday,proto3" json:"highlight_today,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDashboardResponse) Reset()         { *m = GetDashboardResponse{} }
func (m *GetDashboardResponse) String() string { return proto.CompactTextString(m) }
func (*GetDashboardResponse) ProtoMessage()    {}
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *GetDashboardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDashboardResponse.Unmarshal(m, b)
}
func (m *GetDashboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDashboardResponse.Marshal(b, m, deterministic)
}
func (m *GetDashboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDashboardResponse.Merge(m, src)
}
func (m *GetDashboardResponse) XXX_Size() int {
	return xxx_messageInfo_GetDashboardResponse.Size(m)
}
func (m *GetDashboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDashboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDashboardResponse proto.InternalMessageInfo

func (m *GetDashboardResponse) GetNotifications() []*config.Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

func (m *GetDashboardResponse) GetDefaultTab() string {
	if m != nil {
		return m.DefaultTab
	}
	return ""
}

func (m *GetDashboardResponse) GetSuppressFailingTabs() bool {
	if m != nil {
		return m.SuppressFailingTabs
	}
	return false
}

func (m *GetDashboardResponse) GetHighlightToday() bool {
	if m != nil {
		return m.HighlightToday
	}
	return false
}

// GET /dashboardgroups/{dashboardgroup}
// Lists the dashboard names in that group
type GetDashboardGroupResponse struct {
	Dashboards           []*Resource `protobuf:"bytes,1,rep,name=dashboards,proto3" json:"dashboards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetDashboardGroupResponse) Reset()         { *m = GetDashboardGroupResponse{} }
func (m *GetDashboardGroupResponse) String() string { return proto.CompactTextString(m) }
func (*GetDashboardGroupResponse) ProtoMessage()    {}
func (*GetDashboardGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *GetDashboardGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDashboardGroupResponse.Unmarshal(m, b)
}
func (m *GetDashboardGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDashboardGroupResponse.Marshal(b, m, deterministic)
}
func (m *GetDashboardGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDashboardGroupResponse.Merge(m, src)
}
func (m *GetDashboardGroupResponse) XXX_Size() int {
	return xxx_messageInfo_GetDashboardGroupResponse.Size(m)
}
func (m *GetDashboardGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDashboardGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDashboardGroupResponse proto.InternalMessageInfo

func (m *GetDashboardGroupResponse) GetDashboards() []*Resource {
	if m != nil {
		return m.Dashboards
	}
	return nil
}

// GET /testgroups/{testgroup}/headers
// GET /dashboards/{dashboard}/tabs/{tab}/headers
// Returns the headers for grid results
type ListHeadersResponse struct {
	Headers              []*ListHeadersResponse_Header `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ListHeadersResponse) Reset()         { *m = ListHeadersResponse{} }
func (m *ListHeadersResponse) String() string { return proto.CompactTextString(m) }
func (*ListHeadersResponse) ProtoMessage()    {}
func (*ListHeadersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{5}
}

func (m *ListHeadersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHeadersResponse.Unmarshal(m, b)
}
func (m *ListHeadersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHeadersResponse.Marshal(b, m, deterministic)
}
func (m *ListHeadersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHeadersResponse.Merge(m, src)
}
func (m *ListHeadersResponse) XXX_Size() int {
	return xxx_messageInfo_ListHeadersResponse.Size(m)
}
func (m *ListHeadersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHeadersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListHeadersResponse proto.InternalMessageInfo

func (m *ListHeadersResponse) GetHeaders() []*ListHeadersResponse_Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

type ListHeadersResponse_Header struct {
	// Unique instance of the job, typically BUILD_NUMBER from prow or a guid
	Build string `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	// Name associated with the column (such as the run/invocation ID). No two
	// columns should have the same build_id and name. The name field allows the
	// display of multiple columns with the same build_id.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// When the build started running
	Started *timestamp.Timestamp `protobuf:"bytes,3,opt,name=started,proto3" json:"started,omitempty"`
	// Additional custom headers like commit, image used, etc.
	Extra []string `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty"`
	// Custom hotlist ids.
	HotlistIds           string   `protobuf:"bytes,5,opt,name=hotlist_ids,json=hotlistIds,proto3" json:"hotlist_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHeadersResponse_Header) Reset()         { *m = ListHeadersResponse_Header{} }
func (m *ListHeadersResponse_Header) String() string { return proto.CompactTextString(m) }
func (*ListHeadersResponse_Header) ProtoMessage()    {}
func (*ListHeadersResponse_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{5, 0}
}

func (m *ListHeadersResponse_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHeadersResponse_Header.Unmarshal(m, b)
}
func (m *ListHeadersResponse_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHeadersResponse_Header.Marshal(b, m, deterministic)
}
func (m *ListHeadersResponse_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHeadersResponse_Header.Merge(m, src)
}
func (m *ListHeadersResponse_Header) XXX_Size() int {
	return xxx_messageInfo_ListHeadersResponse_Header.Size(m)
}
func (m *ListHeadersResponse_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHeadersResponse_Header.DiscardUnknown(m)
}

var xxx_messageInfo_ListHeadersResponse_Header proto.InternalMessageInfo

func (m *ListHeadersResponse_Header) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func (m *ListHeadersResponse_Header) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListHeadersResponse_Header) GetStarted() *timestamp.Timestamp {
	if m != nil {
		return m.Started
	}
	return nil
}

func (m *ListHeadersResponse_Header) GetExtra() []string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *ListHeadersResponse_Header) GetHotlistIds() string {
	if m != nil {
		return m.HotlistIds
	}
	return ""
}

// GET /testgroups/{testgroup}/rows
// GET /dashboards/{dashboard}/tabs/{tab}/rows
// Returns information on grid rows, and data within those rows
type ListRowsResponse struct {
	Rows                 []*ListRowsResponse_Row `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ListRowsResponse) Reset()         { *m = ListRowsResponse{} }
func (m *ListRowsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRowsResponse) ProtoMessage()    {}
func (*ListRowsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{6}
}

func (m *ListRowsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRowsResponse.Unmarshal(m, b)
}
func (m *ListRowsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRowsResponse.Marshal(b, m, deterministic)
}
func (m *ListRowsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRowsResponse.Merge(m, src)
}
func (m *ListRowsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRowsResponse.Size(m)
}
func (m *ListRowsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRowsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRowsResponse proto.InternalMessageInfo

func (m *ListRowsResponse) GetRows() []*ListRowsResponse_Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type ListRowsResponse_Row struct {
	// Display name of the test case
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Historical results of the test case. Unencoded.
	Cells []*ListRowsResponse_Cell `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`
	// Issue or Bug IDs associated with the test case
	Issues []string `protobuf:"bytes,3,rep,name=issues,proto3" json:"issues,omitempty"`
	// Alert associated with the test case
	Alert                *state.AlertInfo `protobuf:"bytes,4,opt,name=alert,proto3" json:"alert,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListRowsResponse_Row) Reset()         { *m = ListRowsResponse_Row{} }
func (m *ListRowsResponse_Row) String() string { return proto.CompactTextString(m) }
func (*ListRowsResponse_Row) ProtoMessage()    {}
func (*ListRowsResponse_Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{6, 0}
}

func (m *ListRowsResponse_Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRowsResponse_Row.Unmarshal(m, b)
}
func (m *ListRowsResponse_Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRowsResponse_Row.Marshal(b, m, deterministic)
}
func (m *ListRowsResponse_Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRowsResponse_Row.Merge(m, src)
}
func (m *ListRowsResponse_Row) XXX_Size() int {
	return xxx_messageInfo_ListRowsResponse_Row.Size(m)
}
func (m *ListRowsResponse_Row) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRowsResponse_Row.DiscardUnknown(m)
}

var xxx_messageInfo_ListRowsResponse_Row proto.InternalMessageInfo

func (m *ListRowsResponse_Row) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListRowsResponse_Row) GetCells() []*ListRowsResponse_Cell {
	if m != nil {
		return m.Cells
	}
	return nil
}

func (m *ListRowsResponse_Row) GetIssues() []string {
	if m != nil {
		return m.Issues
	}
	return nil
}

func (m *ListRowsResponse_Row) GetAlert() *state.AlertInfo {
	if m != nil {
		return m.Alert
	}
	return nil
}

type ListRowsResponse_Cell struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	CellId               string   `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Icon                 string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRowsResponse_Cell) Reset()         { *m = ListRowsResponse_Cell{} }
func (m *ListRowsResponse_Cell) String() string { return proto.CompactTextString(m) }
func (*ListRowsResponse_Cell) ProtoMessage()    {}
func (*ListRowsResponse_Cell) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{6, 1}
}

func (m *ListRowsResponse_Cell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRowsResponse_Cell.Unmarshal(m, b)
}
func (m *ListRowsResponse_Cell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRowsResponse_Cell.Marshal(b, m, deterministic)
}
func (m *ListRowsResponse_Cell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRowsResponse_Cell.Merge(m, src)
}
func (m *ListRowsResponse_Cell) XXX_Size() int {
	return xxx_messageInfo_ListRowsResponse_Cell.Size(m)
}
func (m *ListRowsResponse_Cell) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRowsResponse_Cell.DiscardUnknown(m)
}

var xxx_messageInfo_ListRowsResponse_Cell proto.InternalMessageInfo

func (m *ListRowsResponse_Cell) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *ListRowsResponse_Cell) GetCellId() string {
	if m != nil {
		return m.CellId
	}
	return ""
}

func (m *ListRowsResponse_Cell) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListRowsResponse_Cell) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

// A Resource is a REST resource, often returned by a LIST command
// It includes the name of the resource and a link to the resource
type Resource struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Link                 string   `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{7}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func init() {
	proto.RegisterType((*ListDashboardResponse)(nil), "testgrid.api.v1.ListDashboardResponse")
	proto.RegisterType((*ListDashboardGroupResponse)(nil), "testgrid.api.v1.ListDashboardGroupResponse")
	proto.RegisterType((*ListDashboardTabsResponse)(nil), "testgrid.api.v1.ListDashboardTabsResponse")
	proto.RegisterType((*GetDashboardResponse)(nil), "testgrid.api.v1.GetDashboardResponse")
	proto.RegisterType((*GetDashboardGroupResponse)(nil), "testgrid.api.v1.GetDashboardGroupResponse")
	proto.RegisterType((*ListHeadersResponse)(nil), "testgrid.api.v1.ListHeadersResponse")
	proto.RegisterType((*ListHeadersResponse_Header)(nil), "testgrid.api.v1.ListHeadersResponse.Header")
	proto.RegisterType((*ListRowsResponse)(nil), "testgrid.api.v1.ListRowsResponse")
	proto.RegisterType((*ListRowsResponse_Row)(nil), "testgrid.api.v1.ListRowsResponse.Row")
	proto.RegisterType((*ListRowsResponse_Cell)(nil), "testgrid.api.v1.ListRowsResponse.Cell")
	proto.RegisterType((*Resource)(nil), "testgrid.api.v1.Resource")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 620 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xdb, 0x8e, 0xd3, 0x3c,
	0x10, 0x56, 0xb6, 0xa7, 0xdd, 0xa9, 0xf6, 0x20, 0xef, 0xe1, 0xcf, 0xf6, 0x66, 0xab, 0x48, 0x3f,
	0xac, 0x84, 0x94, 0x8a, 0x2e, 0x37, 0x48, 0x5c, 0x80, 0x58, 0x58, 0x56, 0x42, 0x5c, 0x58, 0x15,
	0x77, 0xa8, 0x72, 0x6a, 0x37, 0xb5, 0x70, 0xe3, 0x28, 0xe3, 0x50, 0x78, 0x0c, 0x9e, 0x80, 0xd7,
	0x81, 0x97, 0x42, 0xc8, 0x76, 0xd2, 0x4d, 0xa1, 0x12, 0x2b, 0x71, 0x93, 0x78, 0xbe, 0x99, 0xf9,
	0xe6, 0xf0, 0xd9, 0x00, 0x9c, 0x19, 0x16, 0xe7, 0x85, 0x36, 0x9a, 0x1c, 0x1a, 0x81, 0x26, 0x2d,
	0x24, 0x8f, 0x59, 0x2e, 0xe3, 0x4f, 0x8f, 0x07, 0x17, 0xa9, 0xd6, 0xa9, 0x12, 0x23, 0xe7, 0x4e,
	0xca, 0xf9, 0xc8, 0xc8, 0xa5, 0x40, 0xc3, 0x96, 0xb9, 0xcf, 0x18, 0x9c, 0xe5, 0xc9, 0x68, 0xa6,
	0xb3, 0xb9, 0x4c, 0xab, 0x5f, 0x85, 0x9f, 0xe4, 0xc9, 0x08, 0x0d, 0x33, 0xc2, 0x7f, 0x3d, 0x1a,
	0x51, 0x38, 0x7d, 0x2b, 0xd1, 0x5c, 0x33, 0x5c, 0x24, 0x9a, 0x15, 0x9c, 0x0a, 0xcc, 0x75, 0x86,
	0x82, 0x3c, 0xb5, 0x6d, 0x54, 0x20, 0x86, 0xc1, 0xb0, 0x75, 0xd9, 0x1f, 0x9f, 0xc7, 0xbf, 0x75,
	0x13, 0x53, 0x81, 0xba, 0x2c, 0x66, 0x82, 0x36, 0x82, 0xa3, 0x04, 0x06, 0x1b, 0x9c, 0x37, 0x85,
	0x2e, 0xf3, 0x35, 0xf1, 0x35, 0x1c, 0xad, 0x63, 0xa7, 0xa9, 0x75, 0xdd, 0x83, 0xfe, 0x90, 0x6f,
	0x90, 0x61, 0xf4, 0x01, 0xce, 0x37, 0x6a, 0x4c, 0x58, 0x82, 0xeb, 0x12, 0xcf, 0xe1, 0xe0, 0xae,
	0x84, 0x61, 0xc9, 0x3d, 0x0a, 0xec, 0xf3, 0x26, 0x53, 0xf4, 0x23, 0x80, 0x93, 0x1b, 0xb1, 0x65,
	0x2d, 0x57, 0xb0, 0x9f, 0x69, 0x23, 0xe7, 0x72, 0xc6, 0x8c, 0xd4, 0x59, 0xcd, 0xbc, 0x1f, 0xbf,
	0x6b, 0xa0, 0x74, 0x33, 0x86, 0x5c, 0x40, 0x9f, 0x8b, 0x39, 0x2b, 0x95, 0xb1, 0xdd, 0x84, 0x3b,
	0xc3, 0xe0, 0x72, 0x8f, 0x42, 0x05, 0x4d, 0x58, 0x42, 0xc6, 0x70, 0x8a, 0x65, 0x9e, 0x17, 0x02,
	0x71, 0x3a, 0x67, 0x52, 0xc9, 0x2c, 0xf5, 0x7d, 0xb7, 0x86, 0xc1, 0xe5, 0x2e, 0x3d, 0xae, 0x9d,
	0xaf, 0xbd, 0xcf, 0xb6, 0x48, 0x1e, 0xc2, 0xe1, 0x42, 0xa6, 0x0b, 0x25, 0xd3, 0x85, 0x99, 0x1a,
	0xcd, 0xd9, 0x97, 0xb0, 0xed, 0xa2, 0x0f, 0xd6, 0xf0, 0xc4, 0xa2, 0xd1, 0x7b, 0x38, 0x6f, 0x8e,
	0xb2, 0xa9, 0xc6, 0x3f, 0xc8, 0xfc, 0x33, 0x80, 0x63, 0xab, 0xc1, 0x1b, 0xc1, 0xb8, 0x28, 0xee,
	0xb6, 0xff, 0x0a, 0x7a, 0x0b, 0x0f, 0x55, 0x7c, 0x8f, 0xfe, 0xe0, 0xdb, 0x92, 0x16, 0x7b, 0x9b,
	0xd6, 0xb9, 0x83, 0x6f, 0x01, 0x74, 0x3d, 0x46, 0x4e, 0xa0, 0x93, 0x94, 0x52, 0xf1, 0x30, 0x70,
	0x9b, 0xf3, 0x06, 0x21, 0xd0, 0xce, 0xd8, 0x52, 0x54, 0xeb, 0x74, 0x67, 0xf2, 0x04, 0x7a, 0x68,
	0x58, 0x61, 0x04, 0x77, 0xab, 0xeb, 0x8f, 0x07, 0xb1, 0x7f, 0x2f, 0x71, 0xfd, 0x5e, 0xe2, 0x49,
	0xfd, 0x5e, 0x68, 0x1d, 0x6a, 0xf9, 0xc5, 0x67, 0x53, 0xb0, 0xb0, 0x3d, 0x6c, 0x59, 0x7e, 0x67,
	0x58, 0xd5, 0x16, 0xda, 0x28, 0x89, 0x66, 0x2a, 0x39, 0x86, 0x1d, 0xaf, 0x5a, 0x05, 0xdd, 0x72,
	0x8c, 0xbe, 0xef, 0xc0, 0x91, 0x9d, 0x84, 0xea, 0x15, 0x36, 0x16, 0xda, 0x2e, 0xf4, 0xaa, 0x1e,
	0xfd, 0xff, 0xad, 0xa3, 0x37, 0x13, 0x62, 0xaa, 0x57, 0xd4, 0xa5, 0x0c, 0xbe, 0x06, 0xd0, 0xa2,
	0x7a, 0xb5, 0x1e, 0x2c, 0x68, 0x0c, 0xf6, 0x0c, 0x3a, 0x33, 0xa1, 0x14, 0x86, 0x3b, 0x8e, 0xf7,
	0xc1, 0xdf, 0x79, 0x5f, 0x0a, 0xa5, 0xa8, 0x4f, 0x22, 0x67, 0xd0, 0x95, 0x88, 0xa5, 0xb0, 0x17,
	0xca, 0x4e, 0x58, 0x59, 0x64, 0x08, 0x1d, 0xa6, 0x44, 0x61, 0xdc, 0xcd, 0xe9, 0x8f, 0x21, 0x7e,
	0x61, 0xad, 0xdb, 0x6c, 0xae, 0xa9, 0x77, 0x0c, 0x04, 0xb4, 0x2d, 0x91, 0x65, 0x28, 0x04, 0x96,
	0xca, 0xb8, 0xae, 0x3a, 0xb4, 0xb2, 0xc8, 0x7f, 0xd0, 0xb3, 0x25, 0xa6, 0x92, 0x57, 0x3a, 0x74,
	0xad, 0x79, 0xcb, 0x49, 0x08, 0xbd, 0xa5, 0x40, 0x64, 0xa9, 0x70, 0x4a, 0xec, 0xd1, 0xda, 0xb4,
	0xe3, 0xc9, 0x99, 0xce, 0x5c, 0xcd, 0x3d, 0xea, 0xce, 0xd1, 0x18, 0x76, 0xeb, 0x3b, 0xb6, 0x75,
	0x7c, 0x02, 0x6d, 0x25, 0xb3, 0x8f, 0xb5, 0xd6, 0xf6, 0x9c, 0x74, 0x9d, 0xa4, 0x57, 0xbf, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xa3, 0x28, 0x64, 0xec, 0x2f, 0x05, 0x00, 0x00,
}
