---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-summarizer
  namespace: knative
  labels:
    component: summarizer
    app: testgrid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      component: summarizer
  template:
    metadata:
      labels:
        component: summarizer
        app: testgrid
    spec:
      serviceAccountName: summarizer
      containers:
      - name: summarizer
        image: gcr.io/k8s-testgrid/summarizer:v20210402-v0.0.58-6-g7934dd4
        args:
        - --config=gs://knative-own-testgrid/config
        - --confirm
        - --wait=5m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta-summarizer
  namespace: knative
  labels:
    component: summarizer-beta
    app: testgrid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      component: summarizer-beta
  template:
    metadata:
      labels:
        component: summarizer-beta
        app: testgrid
    spec:
      serviceAccountName: summarizer
      containers:
      - name: summarizer
        image: gcr.io/k8s-testgrid/summarizer:v20210402-v0.0.58-6-g7934dd4
        args:
        - --config=gs://knative-own-testgrid/config
        - --confirm
        - --grid-path=grid
        - --summary-path=summary
        - --wait=5m
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Uses same as updater
    iam.gke.io/gcp-service-account: testgrid-updater@knative-tests.iam.gserviceaccount.com
  name: summarizer
  namespace: knative
