---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-summarizer-tabs
  namespace: knative
  labels:
    app: testgrid
    component: summarizer-tabs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      component: summarizer-tabs
  template:
    metadata:
      labels:
        app: testgrid
        component: summarizer-tabs
    spec:
      serviceAccountName: summarizer
      containers:
      - name: summarizer
        image: gcr.io/k8s-testgrid/summarizer:v20220517-v0.0.137-39-gb3934fe7
        ports:
        - name: metrics
          containerPort: 2112
        args:
        - --config=gs://knative-own-testgrid/config
        - --confirm
        - --grid-path=unused
        - --json-logs
        - --persist-queue=gs://knative-own-testgrid/queue/summarizer-tabs.json
        - --pubsub=knative-tests/tab-updates
        - --tab-path=tabs
        - --wait=5m
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Uses same as updater
    iam.gke.io/gcp-service-account: testgrid-updater@knative-tests.iam.gserviceaccount.com
  name: summarizer
  namespace: knative
